# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6fbb2a586b7fc3e1addcc8137d1fef6bf24a8b00d846031f732af6eacfeb4802a40dbb4dfaa8b442a619bd8be6873b7890b5581b7eec76d2ad52faffbde582a5
  MANDRILL_PASSWORD: DNTJA8qZNJqZW-p8Xm3D0Q
  MANDRILL_USERNAME: maksimmamrikov@gmail.com

test:
  secret_key_base: ed81548984f4543391378bf90d01a3a4041f90464c2893c8b3aaa59be75a619b7420547f6cac975ffd5e0386e21f4e021e77c15e6c0d972e6c2d3c0d75843e19

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>