development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE_D"] %>
  some_api_key: <%= ENV["SOME_API_KEY"] %>
  mandrill_password: <%= ENV["MANDRILL_PASSWORD"]%>

test:
  secret_key_base: <%= ENV["SECRET_KEY_BASE_T"] %>
  some_api_key: <%= ENV["SOME_API_KEY"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE_P"] %>
  some_api_key: <%= ENV["SOME_API_KEY"] %>
